import wandb
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

test_cases = {}


test_cases[0] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 2,
    "max_cargo_per_episode": 2,
    "avg_working_capacity": 2,
    "avg_processing_time": 2,
    "soft_deadline_multiplier": 10,
    "hard_deadline_multiplier": 20,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 3,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 5000,
    "max_hard_deadline": 5000,
    "map_type": "plain",
}

test_cases[1] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 2,
    "max_cargo_per_episode": 2,
    "avg_working_capacity": 2.0169,
    "avg_processing_time": 2.1356,
    "soft_deadline_multiplier": 9.9153,
    "hard_deadline_multiplier": 19.7627,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.9831,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4962,
    "max_hard_deadline": 4963,
    "map_type": "plain",
}

test_cases[2] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 2,
    "max_cargo_per_episode": 2,
    "avg_working_capacity": 2.0339,
    "avg_processing_time": 2.2712,
    "soft_deadline_multiplier": 9.8305,
    "hard_deadline_multiplier": 19.5254,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.9661,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4924,
    "max_hard_deadline": 4927,
    "map_type": "plain",
}

test_cases[3] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 2,
    "max_cargo_per_episode": 3,
    "avg_working_capacity": 2.0508,
    "avg_processing_time": 2.4068,
    "soft_deadline_multiplier": 9.7458,
    "hard_deadline_multiplier": 19.2881,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.9492,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4886,
    "max_hard_deadline": 4890,
    "map_type": "plain",
}

test_cases[4] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 2,
    "max_cargo_per_episode": 3,
    "avg_working_capacity": 2.0678,
    "avg_processing_time": 2.5424,
    "soft_deadline_multiplier": 9.661,
    "hard_deadline_multiplier": 19.0508,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.9322,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4849,
    "max_hard_deadline": 4854,
    "map_type": "plain",
}

test_cases[5] = {
    "number_of_agents": 1,
    "number_of_airports": 3,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 3,
    "avg_working_capacity": 2.0847,
    "avg_processing_time": 2.678,
    "soft_deadline_multiplier": 9.5763,
    "hard_deadline_multiplier": 18.8136,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.9153,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4811,
    "max_hard_deadline": 4817,
    "map_type": "plain",
}

test_cases[6] = {
    "number_of_agents": 2,
    "number_of_airports": 3,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 3,
    "avg_working_capacity": 2.1017,
    "avg_processing_time": 2.8136,
    "soft_deadline_multiplier": 9.4915,
    "hard_deadline_multiplier": 18.5763,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8983,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4773,
    "max_hard_deadline": 4781,
    "map_type": "plain",
}

test_cases[7] = {
    "number_of_agents": 2,
    "number_of_airports": 3,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 4,
    "avg_working_capacity": 2.1186,
    "avg_processing_time": 2.9492,
    "soft_deadline_multiplier": 9.4068,
    "hard_deadline_multiplier": 18.339,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8814,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4735,
    "max_hard_deadline": 4744,
    "map_type": "plain",
}

test_cases[8] = {
    "number_of_agents": 2,
    "number_of_airports": 3,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 4,
    "avg_working_capacity": 2.1356,
    "avg_processing_time": 3.0847,
    "soft_deadline_multiplier": 9.322,
    "hard_deadline_multiplier": 18.1017,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8644,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4697,
    "max_hard_deadline": 4708,
    "map_type": "plain",
}

test_cases[9] = {
    "number_of_agents": 2,
    "number_of_airports": 3,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 4,
    "avg_working_capacity": 2.1525,
    "avg_processing_time": 3.2203,
    "soft_deadline_multiplier": 9.2373,
    "hard_deadline_multiplier": 17.8644,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8475,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4659,
    "max_hard_deadline": 4671,
    "map_type": "plain",
}

test_cases[10] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 4,
    "avg_working_capacity": 2.1695,
    "avg_processing_time": 3.3559,
    "soft_deadline_multiplier": 9.1525,
    "hard_deadline_multiplier": 17.6271,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8305,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4622,
    "max_hard_deadline": 4634,
    "map_type": "plain",
}

test_cases[11] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 4,
    "avg_working_capacity": 2.1864,
    "avg_processing_time": 3.4915,
    "soft_deadline_multiplier": 9.0678,
    "hard_deadline_multiplier": 17.3898,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.8136,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4584,
    "max_hard_deadline": 4598,
    "map_type": "plain",
}

test_cases[12] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 5,
    "avg_working_capacity": 2.2034,
    "avg_processing_time": 3.6271,
    "soft_deadline_multiplier": 8.9831,
    "hard_deadline_multiplier": 17.1525,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7966,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4546,
    "max_hard_deadline": 4561,
    "map_type": "plain",
}

test_cases[13] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 5,
    "avg_working_capacity": 2.2203,
    "avg_processing_time": 3.7627,
    "soft_deadline_multiplier": 8.8983,
    "hard_deadline_multiplier": 16.9153,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7797,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4508,
    "max_hard_deadline": 4525,
    "map_type": "plain",
}

test_cases[14] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 3,
    "max_cargo_per_episode": 5,
    "avg_working_capacity": 2.2373,
    "avg_processing_time": 3.8983,
    "soft_deadline_multiplier": 8.8136,
    "hard_deadline_multiplier": 16.678,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7627,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4470,
    "max_hard_deadline": 4488,
    "map_type": "plain",
}

test_cases[15] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 5,
    "avg_working_capacity": 2.2542,
    "avg_processing_time": 4.0339,
    "soft_deadline_multiplier": 8.7288,
    "hard_deadline_multiplier": 16.4407,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7458,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4432,
    "max_hard_deadline": 4452,
    "map_type": "plain",
}

test_cases[16] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 6,
    "avg_working_capacity": 2.2712,
    "avg_processing_time": 4.1695,
    "soft_deadline_multiplier": 8.6441,
    "hard_deadline_multiplier": 16.2034,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7288,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4394,
    "max_hard_deadline": 4415,
    "map_type": "plain",
}

test_cases[17] = {
    "number_of_agents": 2,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 6,
    "avg_working_capacity": 2.2881,
    "avg_processing_time": 4.3051,
    "soft_deadline_multiplier": 8.5593,
    "hard_deadline_multiplier": 15.9661,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.7119,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4357,
    "max_hard_deadline": 4378,
    "map_type": "plain",
}

test_cases[18] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 6,
    "avg_working_capacity": 2.3051,
    "avg_processing_time": 4.4407,
    "soft_deadline_multiplier": 8.4746,
    "hard_deadline_multiplier": 15.7288,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.6949,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4319,
    "max_hard_deadline": 4342,
    "map_type": "plain",
}

test_cases[19] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 6,
    "avg_working_capacity": 2.322,
    "avg_processing_time": 4.5763,
    "soft_deadline_multiplier": 8.3898,
    "hard_deadline_multiplier": 15.4915,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.678,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4281,
    "max_hard_deadline": 4305,
    "map_type": "plain",
}

test_cases[20] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 6,
    "avg_working_capacity": 2.339,
    "avg_processing_time": 4.7119,
    "soft_deadline_multiplier": 8.3051,
    "hard_deadline_multiplier": 15.2542,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.661,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4243,
    "max_hard_deadline": 4269,
    "map_type": "plain",
}

test_cases[21] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 7,
    "avg_working_capacity": 2.3559,
    "avg_processing_time": 4.8475,
    "soft_deadline_multiplier": 8.2203,
    "hard_deadline_multiplier": 15.0169,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.6441,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4205,
    "max_hard_deadline": 4232,
    "map_type": "plain",
}

test_cases[22] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 7,
    "avg_working_capacity": 2.3729,
    "avg_processing_time": 4.9831,
    "soft_deadline_multiplier": 8.1356,
    "hard_deadline_multiplier": 14.7797,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.6271,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4167,
    "max_hard_deadline": 4196,
    "map_type": "plain",
}

test_cases[23] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 7,
    "avg_working_capacity": 2.3898,
    "avg_processing_time": 5.1186,
    "soft_deadline_multiplier": 8.0508,
    "hard_deadline_multiplier": 14.5424,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.6102,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4130,
    "max_hard_deadline": 4159,
    "map_type": "plain",
}

test_cases[24] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 4,
    "max_cargo_per_episode": 7,
    "avg_working_capacity": 2.4068,
    "avg_processing_time": 5.2542,
    "soft_deadline_multiplier": 7.9661,
    "hard_deadline_multiplier": 14.3051,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5932,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4092,
    "max_hard_deadline": 4123,
    "map_type": "plain",
}

test_cases[25] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 8,
    "avg_working_capacity": 2.4237,
    "avg_processing_time": 5.3898,
    "soft_deadline_multiplier": 7.8814,
    "hard_deadline_multiplier": 14.0678,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5763,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4054,
    "max_hard_deadline": 4086,
    "map_type": "plain",
}

test_cases[26] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 8,
    "avg_working_capacity": 2.4407,
    "avg_processing_time": 5.5254,
    "soft_deadline_multiplier": 7.7966,
    "hard_deadline_multiplier": 13.8305,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5593,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 4016,
    "max_hard_deadline": 4049,
    "map_type": "plain",
}

test_cases[27] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 8,
    "avg_working_capacity": 2.4576,
    "avg_processing_time": 5.661,
    "soft_deadline_multiplier": 7.7119,
    "hard_deadline_multiplier": 13.5932,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5424,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3978,
    "max_hard_deadline": 4013,
    "map_type": "plain",
}

test_cases[28] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 8,
    "avg_working_capacity": 2.4746,
    "avg_processing_time": 5.7966,
    "soft_deadline_multiplier": 7.6271,
    "hard_deadline_multiplier": 13.3559,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5254,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3940,
    "max_hard_deadline": 3976,
    "map_type": "plain",
}

test_cases[29] = {
    "number_of_agents": 3,
    "number_of_airports": 4,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 8,
    "avg_working_capacity": 2.4915,
    "avg_processing_time": 5.9322,
    "soft_deadline_multiplier": 7.5424,
    "hard_deadline_multiplier": 13.1186,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.5085,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3902,
    "max_hard_deadline": 3940,
    "map_type": "plain",
}

test_cases[30] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 9,
    "avg_working_capacity": 2.5085,
    "avg_processing_time": 6.0678,
    "soft_deadline_multiplier": 7.4576,
    "hard_deadline_multiplier": 12.8814,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4915,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3865,
    "max_hard_deadline": 3903,
    "map_type": "plain",
}

test_cases[31] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 9,
    "avg_working_capacity": 2.5254,
    "avg_processing_time": 6.2034,
    "soft_deadline_multiplier": 7.3729,
    "hard_deadline_multiplier": 12.6441,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4746,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3827,
    "max_hard_deadline": 3867,
    "map_type": "plain",
}

test_cases[32] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 9,
    "avg_working_capacity": 2.5424,
    "avg_processing_time": 6.339,
    "soft_deadline_multiplier": 7.2881,
    "hard_deadline_multiplier": 12.4068,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4576,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3789,
    "max_hard_deadline": 3830,
    "map_type": "plain",
}

test_cases[33] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 9,
    "avg_working_capacity": 2.5593,
    "avg_processing_time": 6.4746,
    "soft_deadline_multiplier": 7.2034,
    "hard_deadline_multiplier": 12.1695,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4407,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3751,
    "max_hard_deadline": 3794,
    "map_type": "plain",
}

test_cases[34] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 5,
    "max_cargo_per_episode": 9,
    "avg_working_capacity": 2.5763,
    "avg_processing_time": 6.6102,
    "soft_deadline_multiplier": 7.1186,
    "hard_deadline_multiplier": 11.9322,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4237,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3713,
    "max_hard_deadline": 3757,
    "map_type": "plain",
}

test_cases[35] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 10,
    "avg_working_capacity": 2.5932,
    "avg_processing_time": 6.7458,
    "soft_deadline_multiplier": 7.0339,
    "hard_deadline_multiplier": 11.6949,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.4068,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3675,
    "max_hard_deadline": 3720,
    "map_type": "plain",
}

test_cases[36] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 10,
    "avg_working_capacity": 2.6102,
    "avg_processing_time": 6.8814,
    "soft_deadline_multiplier": 6.9492,
    "hard_deadline_multiplier": 11.4576,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.3898,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3637,
    "max_hard_deadline": 3684,
    "map_type": "plain",
}

test_cases[37] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 10,
    "avg_working_capacity": 2.6271,
    "avg_processing_time": 7.0169,
    "soft_deadline_multiplier": 6.8644,
    "hard_deadline_multiplier": 11.2203,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.3729,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3600,
    "max_hard_deadline": 3647,
    "map_type": "plain",
}

test_cases[38] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 10,
    "avg_working_capacity": 2.6441,
    "avg_processing_time": 7.1525,
    "soft_deadline_multiplier": 6.7797,
    "hard_deadline_multiplier": 10.9831,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.3559,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3562,
    "max_hard_deadline": 3611,
    "map_type": "plain",
}

test_cases[39] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 11,
    "avg_working_capacity": 2.661,
    "avg_processing_time": 7.2881,
    "soft_deadline_multiplier": 6.6949,
    "hard_deadline_multiplier": 10.7458,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.339,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3524,
    "max_hard_deadline": 3574,
    "map_type": "plain",
}

test_cases[40] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 11,
    "avg_working_capacity": 2.678,
    "avg_processing_time": 7.4237,
    "soft_deadline_multiplier": 6.6102,
    "hard_deadline_multiplier": 10.5085,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.322,
    "malfunction_rate": 0,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 0,
    "max_soft_deadline": 3486,
    "max_hard_deadline": 3538,
    "map_type": "plain",
}

test_cases[41] = {
    "number_of_agents": 4,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 11,
    "avg_working_capacity": 2.6949,
    "avg_processing_time": 7.5593,
    "soft_deadline_multiplier": 6.5254,
    "hard_deadline_multiplier": 10.2712,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.3051,
    "malfunction_rate": 0.0079,
    "malfunction_min_steps": 0,
    "malfunction_max_steps": 1,
    "max_soft_deadline": 3448,
    "max_hard_deadline": 3501,
    "map_type": "plain",
}

test_cases[42] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 11,
    "avg_working_capacity": 2.7119,
    "avg_processing_time": 7.6949,
    "soft_deadline_multiplier": 6.4407,
    "hard_deadline_multiplier": 10.0339,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2881,
    "malfunction_rate": 0.0158,
    "malfunction_min_steps": 1,
    "malfunction_max_steps": 3,
    "max_soft_deadline": 3410,
    "max_hard_deadline": 3465,
    "map_type": "plain",
}

test_cases[43] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 11,
    "avg_working_capacity": 2.7288,
    "avg_processing_time": 7.8305,
    "soft_deadline_multiplier": 6.3559,
    "hard_deadline_multiplier": 9.7966,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2712,
    "malfunction_rate": 0.0237,
    "malfunction_min_steps": 1,
    "malfunction_max_steps": 4,
    "max_soft_deadline": 3373,
    "max_hard_deadline": 3428,
    "map_type": "plain",
}

test_cases[44] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 6,
    "max_cargo_per_episode": 12,
    "avg_working_capacity": 2.7458,
    "avg_processing_time": 7.9661,
    "soft_deadline_multiplier": 6.2712,
    "hard_deadline_multiplier": 9.5593,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2542,
    "malfunction_rate": 0.0316,
    "malfunction_min_steps": 1,
    "malfunction_max_steps": 6,
    "max_soft_deadline": 3335,
    "max_hard_deadline": 3391,
    "map_type": "plain",
}

test_cases[45] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 12,
    "avg_working_capacity": 2.7627,
    "avg_processing_time": 8.1017,
    "soft_deadline_multiplier": 6.1864,
    "hard_deadline_multiplier": 9.322,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2373,
    "malfunction_rate": 0.0395,
    "malfunction_min_steps": 2,
    "malfunction_max_steps": 7,
    "max_soft_deadline": 3297,
    "max_hard_deadline": 3355,
    "map_type": "plain",
}

test_cases[46] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 12,
    "avg_working_capacity": 2.7797,
    "avg_processing_time": 8.2373,
    "soft_deadline_multiplier": 6.1017,
    "hard_deadline_multiplier": 9.0847,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2203,
    "malfunction_rate": 0.0474,
    "malfunction_min_steps": 2,
    "malfunction_max_steps": 9,
    "max_soft_deadline": 3259,
    "max_hard_deadline": 3318,
    "map_type": "plain",
}

test_cases[47] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 12,
    "avg_working_capacity": 2.7966,
    "avg_processing_time": 8.3729,
    "soft_deadline_multiplier": 6.0169,
    "hard_deadline_multiplier": 8.8475,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.2034,
    "malfunction_rate": 0.0553,
    "malfunction_min_steps": 3,
    "malfunction_max_steps": 10,
    "max_soft_deadline": 3221,
    "max_hard_deadline": 3282,
    "map_type": "plain",
}

test_cases[48] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 13,
    "avg_working_capacity": 2.8136,
    "avg_processing_time": 8.5085,
    "soft_deadline_multiplier": 5.9322,
    "hard_deadline_multiplier": 8.6102,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1864,
    "malfunction_rate": 0.0632,
    "malfunction_min_steps": 3,
    "malfunction_max_steps": 12,
    "max_soft_deadline": 3183,
    "max_hard_deadline": 3245,
    "map_type": "plain",
}

test_cases[49] = {
    "number_of_agents": 5,
    "number_of_airports": 5,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 13,
    "avg_working_capacity": 2.8305,
    "avg_processing_time": 8.6441,
    "soft_deadline_multiplier": 5.8475,
    "hard_deadline_multiplier": 8.3729,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1695,
    "malfunction_rate": 0.0711,
    "malfunction_min_steps": 3,
    "malfunction_max_steps": 13,
    "max_soft_deadline": 3145,
    "max_hard_deadline": 3209,
    "map_type": "plain",
}

test_cases[50] = {
    "number_of_agents": 5,
    "number_of_airports": 6,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 13,
    "avg_working_capacity": 2.8475,
    "avg_processing_time": 8.7797,
    "soft_deadline_multiplier": 5.7627,
    "hard_deadline_multiplier": 8.1356,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1525,
    "malfunction_rate": 0.0789,
    "malfunction_min_steps": 4,
    "malfunction_max_steps": 15,
    "max_soft_deadline": 3108,
    "max_hard_deadline": 3172,
    "map_type": "plain",
}

test_cases[51] = {
    "number_of_agents": 5,
    "number_of_airports": 6,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 13,
    "avg_working_capacity": 2.8644,
    "avg_processing_time": 8.9153,
    "soft_deadline_multiplier": 5.678,
    "hard_deadline_multiplier": 7.8983,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1356,
    "malfunction_rate": 0.0868,
    "malfunction_min_steps": 4,
    "malfunction_max_steps": 16,
    "max_soft_deadline": 3070,
    "max_hard_deadline": 3135,
    "map_type": "plain",
}

test_cases[52] = {
    "number_of_agents": 5,
    "number_of_airports": 6,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 13,
    "avg_working_capacity": 2.8814,
    "avg_processing_time": 9.0508,
    "soft_deadline_multiplier": 5.5932,
    "hard_deadline_multiplier": 7.661,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1186,
    "malfunction_rate": 0.0947,
    "malfunction_min_steps": 4,
    "malfunction_max_steps": 18,
    "max_soft_deadline": 3032,
    "max_hard_deadline": 3099,
    "map_type": "plain",
}

test_cases[53] = {
    "number_of_agents": 5,
    "number_of_airports": 6,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 14,
    "avg_working_capacity": 2.8983,
    "avg_processing_time": 9.1864,
    "soft_deadline_multiplier": 5.5085,
    "hard_deadline_multiplier": 7.4237,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.1017,
    "malfunction_rate": 0.1026,
    "malfunction_min_steps": 5,
    "malfunction_max_steps": 19,
    "max_soft_deadline": 2994,
    "max_hard_deadline": 3062,
    "map_type": "plain",
}

test_cases[54] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 7,
    "max_cargo_per_episode": 14,
    "avg_working_capacity": 2.9153,
    "avg_processing_time": 9.322,
    "soft_deadline_multiplier": 5.4237,
    "hard_deadline_multiplier": 7.1864,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.0847,
    "malfunction_rate": 0.1105,
    "malfunction_min_steps": 5,
    "malfunction_max_steps": 21,
    "max_soft_deadline": 2956,
    "max_hard_deadline": 3026,
    "map_type": "plain",
}

test_cases[55] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 8,
    "max_cargo_per_episode": 14,
    "avg_working_capacity": 2.9322,
    "avg_processing_time": 9.4576,
    "soft_deadline_multiplier": 5.339,
    "hard_deadline_multiplier": 6.9492,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.0678,
    "malfunction_rate": 0.1184,
    "malfunction_min_steps": 6,
    "malfunction_max_steps": 22,
    "max_soft_deadline": 2918,
    "max_hard_deadline": 2989,
    "map_type": "plain",
}

test_cases[56] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 8,
    "max_cargo_per_episode": 14,
    "avg_working_capacity": 2.9492,
    "avg_processing_time": 9.5932,
    "soft_deadline_multiplier": 5.2542,
    "hard_deadline_multiplier": 6.7119,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.0508,
    "malfunction_rate": 0.1263,
    "malfunction_min_steps": 6,
    "malfunction_max_steps": 24,
    "max_soft_deadline": 2881,
    "max_hard_deadline": 2953,
    "map_type": "plain",
}

test_cases[57] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 8,
    "max_cargo_per_episode": 15,
    "avg_working_capacity": 2.9661,
    "avg_processing_time": 9.7288,
    "soft_deadline_multiplier": 5.1695,
    "hard_deadline_multiplier": 6.4746,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.0339,
    "malfunction_rate": 0.1342,
    "malfunction_min_steps": 6,
    "malfunction_max_steps": 25,
    "max_soft_deadline": 2843,
    "max_hard_deadline": 2916,
    "map_type": "plain",
}

test_cases[58] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 8,
    "max_cargo_per_episode": 15,
    "avg_working_capacity": 2.9831,
    "avg_processing_time": 9.8644,
    "soft_deadline_multiplier": 5.0847,
    "hard_deadline_multiplier": 6.2373,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2.0169,
    "malfunction_rate": 0.1421,
    "malfunction_min_steps": 7,
    "malfunction_max_steps": 27,
    "max_soft_deadline": 2805,
    "max_hard_deadline": 2880,
    "map_type": "plain",
}

test_cases[59] = {
    "number_of_agents": 6,
    "number_of_airports": 6,
    "number_of_initial_cargo": 8,
    "max_cargo_per_episode": 15,
    "avg_working_capacity": 3,
    "avg_processing_time": 10.0,
    "soft_deadline_multiplier": 5,
    "hard_deadline_multiplier": 6,
    "min_degree": 2,
    "max_degree": 3,
    "route_ratio": 2,
    "malfunction_rate": 0.15,
    "malfunction_min_steps": 7,
    "malfunction_max_steps": 28,
    "max_soft_deadline": 2767,
    "max_hard_deadline": 2843,
    "map_type": "plain",
}

# Convert dictionary to DataFrame (each test case as a row)
df = pd.DataFrame.from_dict(test_cases, orient="index")

# Reset index to make test case number a column
df.index.name = "test_case_id"
df = df.reset_index()

# Save to CSV
df.to_csv("csv/curriculum_test_cases.csv", index=False)

print(f"Saved {len(df)} test cases to csv/curriculum_test_cases.csv")
print(f"\nDataFrame shape: {df.shape}")
print(f"\nFirst few rows:")
print(df.head())

# Calculate dynamic cargo
df["dynamic_cargo"] = df["max_cargo_per_episode"] - df["number_of_initial_cargo"]

# Create plots
single_metrics = [
    ("number_of_agents", "Number of Agents"),
    ("number_of_airports", "Number of Airports"),
    ("malfunction_rate", "Malfunction Rate"),
]
cargo_metrics = [
    ("number_of_initial_cargo", "Initial Cargo"),
    ("dynamic_cargo", "Dynamic Cargo"),
]

fig, axes = plt.subplots(2, 2, figsize=(14, 10), sharex=True)
axes = axes.flatten()

cargo_ax = axes[3]  # dedicate axis for cargo plot

# 1) Plot the three single metrics
for plot_ax, (metric_key, metric_label) in zip(axes[:3], single_metrics):
    plot_ax.plot(df["test_case_id"], df[metric_key], color="tab:blue")
    plot_ax.set_title(metric_label)
    plot_ax.set_ylabel(metric_label)
    plot_ax.grid(True)
    plot_ax.set_xticks(df["test_case_id"][::5])
    plot_ax.tick_params(labelbottom=True)

# 2) Combined cargo plot
for metric_key, short_label in cargo_metrics:
    is_dynamic = "dynamic" in metric_key.lower()
    linestyle = "--" if is_dynamic else "-"

    cargo_ax.plot(
        df["test_case_id"],
        df[metric_key],
        label=short_label,
        linestyle=linestyle,
    )

cargo_ax.set_title("Cargo")
cargo_ax.set_ylabel("Cargo Count")
cargo_ax.grid(True)
cargo_ax.legend(loc="best")
cargo_ax.set_xticks(df["test_case_id"][::5])
cargo_ax.tick_params(labelbottom=True)

# common x labels
for plot_ax in axes:
    plot_ax.set_xlabel("Test Case ID")

fig.suptitle("Curriculum Test Case Parameters", fontsize=16)
fig.tight_layout(rect=[0, 0.03, 1, 0.95])

fig.savefig("figs/curriculum_test_cases.png", dpi=300, bbox_inches="tight")
plt.close(fig)

print("\nPlot saved to figs/curriculum_test_cases.png")
